/* Main.c file generated by New Project wizard
 *
 * Created:   Fri Sep 17 2021
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>
#include <sysinit.h>
#include <keypad.h>


void delay_app(uint16_t time);

void delay_app(uint16_t time)
{
	volatile unsigned long l = 0;
	uint16_t i;
	for (i = 0; i < time; i++)
	{
		for (l; l < 6000; l++);
	}
}

uint8_t lastkey = 0;

int main (void)
{
   	uint8_t key;
	 key = 0;
	gpio_init();
	keypad_init();


	while(1)
	{
		if (keypad_update(&key))
		{
			lastkey = key;
		}
		delay_app(100);
	}
}
