/* Main.c file generated by New Project wizard
 *
 * Created:   Fri Sep 10 2021
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>
#include <sysinit.h>
#include <keypad.h>
#include <lcd.h>
#include <delay.h>
#include <seos.h>

void SysTick_Handler(void) 
{
    seos_schedule_tasks();
}

int main (void)
{
	gpio_init();
	keypad_init();
	lcd_init();
	SysTick_Config(SystemCoreClock / 1000);

	while(1)
	{
		seos_dispatch_tasks();
	}
}
