/* Main.c file generated by New Project wizard
 *
 * Created:   Fri Sep 17 2021
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>

void delay_app(uint16_t time);

void delay_app(uint16_t time)
{
	volatile unsigned long l = 0;
	uint16_t i;
	for (i = 0; i < time; i++);
	for (l; l < 6000; l++);
}

int main (void)
{
	RCC -> APB2ENR |= 0xfc;
	GPIOC -> CRH = 0x44344444;
	while(1)
	{
		GPIOC -> ODR ^= (1<<13);
		delay_app(10);
	}
}
