/* Main.c file generated by New Project wizard
 *
 * Created:   Fri Sep 17 2021
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>
#include <sysinit.h>
#include <keypad.h>
#include <lcd.h>
#include <delay.h>


void delay_app(uint16_t time);

void delay_app(uint16_t time)
{
	volatile unsigned long l = 0;
	uint16_t i;
	for (i = 0; i < time; i++)
	{
		for (l; l < 6000; l++);
	}
}

uint8_t lastkey = 0;

int main (void)
{
   	uint8_t key;
	 key = 0;
	gpio_init();
	keypad_init();
	lcd_init();
   
	 lcd_send_data('H');
	 lcd_send_data('e');
	 lcd_send_data('l');
	 lcd_send_data('l');
	 lcd_send_data('o');
   


	while(1)
	{
		if (keypad_update(&key))
		{
			lastkey = key;
			lcd_send_cmd(0x02);/* clear LCD */
			delay_us(2000);
			lcd_send_data(lastkey);
		}
		delay_ms(100);
	}
}
